-- 
USE DATABASE AIX_SHARED_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE VIEW VW_USER_ORDERS AS
SELECT 
    u.USER_ID,
    u.USERNAME,
    u.EMAIL,
    COUNT(*) as TOTAL_ORDERS,
    SUM(o.ORDER_AMOUNT) as TOTAL_SPENT,
    MAX(o.ORDER_DATE) as LAST_ORDER_DATE
FROM USERS u
LEFT JOIN ORDERS o ON u.USER_ID = o.USER_ID
WHERE u.IS_ACTIVE = TRUE
GROUP BY u.USER_ID, u.USERNAME, u.EMAIL
ORDER BY TOTAL_SPENT DESC;

-- git push TEST monitor
COMMENT ON VIEW VW_USER_ORDERS IS 'Summary view of user order statistics';
