-- Safe table with indexes - should get SAFE rating
USE DATABASE AIX_SHARED_DB;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_DESCRIPTION TEXT,
    CATEGORY VARCHAR(50),
    PRICE NUMBER(10,2) NOT NULL,
    SKU VARCHAR(50) UNIQUE,
    IN_STOCK BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_CATEGORY ON PRODUCTS(CATEGORY);
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_SKU ON PRODUCTS(SKU);
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_PRICE ON PRODUCTS(PRICE);

COMMENT ON TABLE PRODUCTS IS 'Product catalog information';