-- Safe table creation - should get SAFE rating
USE DATABASE AIX_SHARED_DB;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

COMMENT ON TABLE USERS IS 'User account information for the application';
COMMENT ON COLUMN USERS.USER_ID IS 'Unique identifier for each user';
COMMENT ON COLUMN USERS.USERNAME IS 'Unique username for login';